name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Configure Git for private repos
        run: |
          git config --global url."https://${{ secrets.REPO_PAT }}@github.com/".insteadOf "https://github.com/"
          go env -w GOPRIVATE=github.com/AI-Template-SDK/*
      - name: Build Server
        run: go build .